name: CI

on:
  push:
    branches:
      - "release/*"
      - develop
      - main
  pull_request:
    branches: [develop, main]

permissions:
  contents: write
  packages: write

jobs:
  ci:
    uses: mario-noobs/ci-baseline/.github/workflows/_ci-node.yml@main
    with:
      package_manager: pnpm
      node_version: "20"
      lint_enabled: true
      test_enabled: false

  docker:
    needs: ci
    if: github.event_name == 'push'
    uses: mario-noobs/ci-baseline/.github/workflows/_docker-build.yml@main
    with:
      image_name: gui-app
      context: "."
